M48
; DRILL file {KiCad 7.0.9} date Sat 10 Feb 2024 12:43:48 AM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-10T00:43:48-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X176.545Y-105.525
X176.545Y-110.375
T2
X179.575Y-105.225
X179.575Y-110.675
T0
M30
